-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUeqKIHOK238GjxcH
eatXLO7u32L1Y+mlQQEZycKOiM6gCgYIKoZIzj0DAQehRANCAARMPgGzEumDWdO2
kb2WjXW1b8ji5yrvgVByE2WCaTdRPdjzvYxMKlSM8nSueismOIeSdpWzcD/2iQ3h
oJJ+KnQ1
-----END PRIVATE KEY-----