# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'The Edge Daily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  rn_path = '../node_modules/react-native'

  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
			if target.name == 'yoga'
				target.remove_from_project
				target.build_configurations.each do |config|
						config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
						config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
				end
			end
    end
  end

end

target 'The Edge Daily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for The Edge Daily-tvOS

  target 'The Edge Daily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
