# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'The Edge Daily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  target 'The Edge DailyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'The Edge Daily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for The Edge Daily-tvOS

  target 'The Edge Daily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
